# -*- coding: utf-8 -*-
"""subway_칸별혼잡도_.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWGLWNobfCq-z3JOt-1jJrFmTdsI7sC9
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import os

# --------------------------
# 1. 데이터 로드 및 통합
# --------------------------

data_folder = 'data_files'
all_files = [os.path.join(data_folder, f) for f in os.listdir(data_folder) if f.endswith('.csv')]

if not all_files:
    print(f"오류: '{data_folder}' 폴더에 CSV 파일이 없습니다. 경로와 파일명을 확인해 주세요.")
    exit()

list_df = []
for filename in all_files:
    try:
        df = pd.read_csv(filename)
        list_df.append(df)
    except Exception as e:
        print(f"경고: 파일 {filename} 읽기 실패. 오류: {e}")

df_raw = pd.concat(list_df, ignore_index=True)
print(f"총 {len(all_files)}개 파일을 통합하여 {len(df_raw)}개 데이터 확보 완료.")

# --------------------------
# 2. 데이터 구조 변환 (Wide -> Long) 및 종속 변수(Y) 정의
# --------------------------

congestion_cols = {f'혼잡도{i}': f'칸{i}' for i in range(1, 11)}

df_long = df_raw.melt(
    id_vars=[col for col in df_raw.columns if col not in congestion_cols],
    value_vars=congestion_cols.keys(),
    var_name='칸_컬럼명',
    value_name='혼잡도_퍼센트'
)

df_long['칸_번호'] = df_long['칸_컬럼명'].str.extract('(\d+)').astype(int)
df_long['승객_수'] = df_long['혼잡도_퍼센트'] * 1.6
Y_new = df_long['승객_수']
print(f"Long Format 변환 완료. 총 {len(df_long)}개 (기존 대비 10배) 데이터 포인트 확보.")

# --------------------------
# 3. 독립 변수(X) 정의 및 생성 (칸 번호 추가)
# --------------------------

TRANSFER_STATIONS = ['신도림역', '사당역']
BUSINESS_DISTRICTS = ['강남역', '여의도역', '서울역']

df_long['AM_Peak'] = np.where(df_long['시간(시)'].isin([8]), 1, 0)
df_long['PM_Peak'] = np.where(df_long['시간(시)'].isin([18, 19]), 1, 0)
df_long['Transfer_Station'] = np.where(df_long['기준_역명'].isin(TRANSFER_STATIONS), 1, 0)
df_long['Business_District'] = np.where(df_long['기준_역명'].isin(BUSINESS_DISTRICTS), 1, 0)

line_dummies = pd.get_dummies(df_long['노선'], prefix='Line', drop_first=True)
df_features_new = pd.concat([df_long, line_dummies], axis=1)

X_cols_new = [
    'AM_Peak', 'PM_Peak',
    'Transfer_Station', 'Business_District',
    '칸_번호'
]
X_cols_new.extend([col for col in line_dummies.columns if col in df_features_new.columns])

X_new = df_features_new[X_cols_new]
print(f"독립 변수(X) {X_new.shape[1]}개 생성 완료. (칸_번호 추가)")


# --------------------------
# 4. 모델 학습 (다중 선형 회귀 - OLS)
# --------------------------

X_with_const_new = sm.add_constant(X_new, has_constant='add')
model_kan = sm.OLS(Y_new, X_with_const_new).fit()

print("\n" + "="*50)
print("     [칸 별 혼잡도 예측 모델 학습 결과 (OLS)]")
print("="*50)
print(model_kan.summary().as_text())

# ----------------------------------------------------------------------
# 5. 예측 함수 및 예시 (10개 칸을 하나의 입력으로 한 번에 예측)
# ----------------------------------------------------------------------

def predict_train_congestion(model, X_cols, train_features):
    """
    하나의 열차 운행 특징(train_features)에 대해 1번 칸부터 10번 칸까지
    모두 예측하여 DataFrame 형태로 반환합니다.
    """

    car_numbers = list(range(1, 11))
    input_data_list = []
    feature_names = ['const'] + X_cols

    # 1. 10개 칸에 대한 입력 데이터를 한 번에 준비
    for car_num in car_numbers:
        input_row = {name: 0 for name in feature_names}
        input_row['const'] = 1

        # 2. 열차 공통 특징 (시간대, 노선 등) 적용
        for key, value in train_features.items():
            if key in input_row:
                input_row[key] = value

        # 3. 핵심: 각 행에 '칸_번호'만 1부터 10까지 다르게 넣어줌
        input_row['칸_번호'] = car_num

        # 모델의 변수 순서에 맞게 값을 정렬하여 리스트에 추가
        ordered_input_values = [input_row[name] for name in feature_names]
        input_data_list.append(ordered_input_values)

    # 4. NumPy 배열로 변환 후 모델에 한 번에 예측 요청
    X_predict = np.array(input_data_list)
    predictions_passengers = model.predict(X_predict)

    # 5. 결과 DataFrame 생성 및 반환
    df_results = pd.DataFrame({
        '칸 번호': car_numbers,
        '예상 승객 수': predictions_passengers.round(1).astype(str) + '명',
        '예상 혼잡도': (predictions_passengers / 1.6).round(1).astype(str) + '%'
    })

    return df_results

# --- 예측 시나리오: 2호선 퇴근길 (18:30 PM)의 혼잡도 예측 ---
# (이 딕셔너리는 10개 칸에 모두 공통으로 적용될 운행 특징임)
seoul_to_sillim_features = {
    'AM_Peak': 0,
    'PM_Peak': 1, # 퇴근 피크!
    'Transfer_Station': 0,
    'Business_District': 0,
    'Line_2호선': 1, # 2호선
    # 주의: 데이터에 Line_2호선 외 다른 노선이 있다면, 해당 노선만 1로 설정해야 함
}

# 10개 칸 예측을 한 번에 출력
df_all_cars_results = predict_train_congestion(model_kan, X_cols_new, seoul_to_sillim_features)

print("\n" + "="*50)
print("      [특정 열차의 1번 칸부터 10번 칸까지 한 번에 예측]")
print("="*50)
print("운행 정보: 2호선, 18:30 PM (퇴근 피크), 일반 역 기준")
print(df_all_cars_results)
print("--------------------------------------------------")